// Seed data for well-known congress members with Korean name translations
// Korean names sourced from official Korean media transliterations

export interface PoliticianSeed {
  bioguideId: string;
  firstName: string;
  lastName: string;
  nameEn: string;
  nameKr: string;
  party: 'Republican' | 'Democrat' | 'Independent';
  chamber: 'senate' | 'house';
  state: string;
  district?: number;
  slug: string;
}

export const POLITICIAN_SEEDS: PoliticianSeed[] = [
  // Senate
  {
    bioguideId: 'P000197',
    firstName: 'Nancy',
    lastName: 'Pelosi',
    nameEn: 'Nancy Pelosi',
    nameKr: '낸시 펠로시',
    party: 'Democrat',
    chamber: 'house',
    state: 'CA',
    district: 11,
    slug: 'nancy-pelosi',
  },
  {
    bioguideId: 'B001243',
    firstName: 'Marsha',
    lastName: 'Blackburn',
    nameEn: 'Marsha Blackburn',
    nameKr: '마샤 블랙번',
    party: 'Republican',
    chamber: 'senate',
    state: 'TN',
    slug: 'marsha-blackburn',
  },
  {
    bioguideId: 'T000250',
    firstName: 'Tommy',
    lastName: 'Tuberville',
    nameEn: 'Tommy Tuberville',
    nameKr: '토미 튜버빌',
    party: 'Republican',
    chamber: 'senate',
    state: 'AL',
    slug: 'tommy-tuberville',
  },
  {
    bioguideId: 'B001310',
    firstName: 'Mike',
    lastName: 'Braun',
    nameEn: 'Mike Braun',
    nameKr: '마이크 브라운',
    party: 'Republican',
    chamber: 'senate',
    state: 'IN',
    slug: 'mike-braun',
  },
  {
    bioguideId: 'L000571',
    firstName: 'Cynthia',
    lastName: 'Lummis',
    nameEn: 'Cynthia Lummis',
    nameKr: '신시아 루미스',
    party: 'Republican',
    chamber: 'senate',
    state: 'WY',
    slug: 'cynthia-lummis',
  },
  {
    bioguideId: 'K000393',
    firstName: 'John',
    lastName: 'Kennedy',
    nameEn: 'John Kennedy',
    nameKr: '존 케네디',
    party: 'Republican',
    chamber: 'senate',
    state: 'LA',
    slug: 'john-kennedy',
  },
  {
    bioguideId: 'C001095',
    firstName: 'Tom',
    lastName: 'Cotton',
    nameEn: 'Tom Cotton',
    nameKr: '톰 코튼',
    party: 'Republican',
    chamber: 'senate',
    state: 'AR',
    slug: 'tom-cotton',
  },
  {
    bioguideId: 'O000174',
    firstName: 'Jon',
    lastName: 'Ossoff',
    nameEn: 'Jon Ossoff',
    nameKr: '존 오소프',
    party: 'Democrat',
    chamber: 'senate',
    state: 'GA',
    slug: 'jon-ossoff',
  },
  {
    bioguideId: 'S001181',
    firstName: 'Jeanne',
    lastName: 'Shaheen',
    nameEn: 'Jeanne Shaheen',
    nameKr: '진 샤힌',
    party: 'Democrat',
    chamber: 'senate',
    state: 'NH',
    slug: 'jeanne-shaheen',
  },
  {
    bioguideId: 'W000817',
    firstName: 'Elizabeth',
    lastName: 'Warren',
    nameEn: 'Elizabeth Warren',
    nameKr: '엘리자베스 워런',
    party: 'Democrat',
    chamber: 'senate',
    state: 'MA',
    slug: 'elizabeth-warren',
  },
  // House
  {
    bioguideId: 'G000596',
    firstName: 'Marjorie Taylor',
    lastName: 'Greene',
    nameEn: 'Marjorie Taylor Greene',
    nameKr: '마조리 테일러 그린',
    party: 'Republican',
    chamber: 'house',
    state: 'GA',
    district: 14,
    slug: 'marjorie-taylor-greene',
  },
  {
    bioguideId: 'S000522',
    firstName: 'Christopher H.',
    lastName: 'Smith',
    nameEn: 'Christopher Smith',
    nameKr: '크리스토퍼 스미스',
    party: 'Republican',
    chamber: 'house',
    state: 'NJ',
    district: 4,
    slug: 'christopher-smith',
  },
  {
    bioguideId: 'S001196',
    firstName: 'Elise',
    lastName: 'Stefanik',
    nameEn: 'Elise Stefanik',
    nameKr: '엘리스 스테파닉',
    party: 'Republican',
    chamber: 'house',
    state: 'NY',
    district: 21,
    slug: 'elise-stefanik',
  },
  {
    bioguideId: 'A000377',
    firstName: 'Rick',
    lastName: 'Allen',
    nameEn: 'Rick Allen',
    nameKr: '릭 앨런',
    party: 'Republican',
    chamber: 'house',
    state: 'GA',
    district: 12,
    slug: 'rick-allen',
  },
  {
    bioguideId: 'C001072',
    firstName: 'André',
    lastName: 'Carson',
    nameEn: 'André Carson',
    nameKr: '앙드레 카슨',
    party: 'Democrat',
    chamber: 'house',
    state: 'IN',
    district: 7,
    slug: 'andre-carson',
  },
];
